<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-O4OM8TU" failures="1" tests="7" name="tests.TestNgSuiteRunner" time="3.626" errors="0" timestamp="2021-10-17T23:17:35 BRT" skipped="0">
  <testcase classname="tests.TestNgSuiteRunner" name="runScenario" time="3.331"/>
  <system-out/>
  <testcase classname="tests.TestNgSuiteRunner" name="runScenario" time="0.026">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.features.steps.Third.enterLogInData(Third.java:27)
at âœ½.user enters the "Natan" and "12312" credentials(classpath:tests/features/Third.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="tests.TestNgSuiteRunner" name="runScenario" time="0.028"/>
  <system-out/>
  <testcase classname="tests.TestNgSuiteRunner" name="runScenario" time="0.019"/>
  <system-out/>
  <testcase classname="tests.TestNgSuiteRunner" name="runScenario" time="0.192"/>
  <system-out/>
  <testcase classname="tests.TestNgSuiteRunner" name="runScenario" time="0.013"/>
  <system-out/>
  <testcase classname="tests.TestNgSuiteRunner" name="runScenario" time="0.017"/>
  <system-out/>
</testsuite> <!-- tests.TestNgSuiteRunner -->
